[auth.external.google]
enabled = true
client_id = "996700389903-8as4h5i1nuej7n644ara1kb39pm0me0d.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false